#:schema node_modules/wrangler/config-schema.json
name = "gift-list-tracker"
main = "src/index.ts"
compatibility_date = "2024-11-06"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[observability.logs]
enabled = true

# Define Durable Object namespaces
[[durable_objects.bindings]]
name = "GIFT_LIST_STORE" # This matches the binding in your code
class_name = "GiftListStore"

[[migrations]]
tag = "v1"
new_classes = [ "GiftListStore" ]
